apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-dsp-testjul16-9-test-gitops
spec:  
  template:         
    metadata:
      name: initialize-dsp-testjul16-9-test-gitops
    spec:  
      serviceAccountName: testjul16-9-test-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-appstudio/appstudio-utils:5bd7d6cb0b17f9f2eab043a8ad16ba3d90551bc2@sha256:8c7fcf86af40c71aeb58e4279625c8308af5144e2f6b8e28b0ec7e795260e5f7

        command:
        - /bin/bash
        - -c
        - |
          # Wait for the NS initialize job to finish
          echo "Wait for NS Job"
          oc wait --for=condition=complete job/initialize-namespace-testjul16-9-test-gitops
          echo "Done"

          # Label the namespace as a DataScienceProject
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc label ns $NS opendatahub.io/dashboard=true --overwrite

          # Retrieve the UID for the notebook SA, and mark the notebook as owned by it for garbage collection purposes
          SA_UID=$(oc get sa testjul16-9-test-dsp-job -o json | jq -r .metadata.uid)
          echo "$SA_UID"
          cat <<EOF | oc apply -f -
          apiVersion: kubeflow.org/v1
          kind: Notebook
          metadata:
            annotations:
              notebooks.opendatahub.io/inject-oauth: 'true'
              opendatahub.io/image-display-name: Minimal Python
              notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.apps.jcollier-rhoaijul1521.devcluster.openshift.com/projects/rhtap-app?notebookLogout=testjul16-9-test
              opendatahub.io/accelerator-name: ''
              openshift.io/description: ''
              openshift.io/display-name: testjul16-9-test
              notebooks.opendatahub.io/last-image-selection: 's2i-minimal-notebook:2024.1'
              notebooks.opendatahub.io/last-size-selection: Small
            name: testjul16-9-test
            namespace: rhtap-app
            ownerReferences:
              - apiVersion: v1
                kind: ServiceAccount
                name: testjul16-9-test-dsp-job
                uid: $SA_UID
            labels:
              app: testjul16-9-test
              opendatahub.io/dashboard: 'true'
              opendatahub.io/odh-managed: 'true'
          spec:
            template:
              spec:
                affinity: {}
                containers:
                  - resources:
                      limits:
                        cpu: '2'
                        memory: 8Gi
                      requests:
                        cpu: '1'
                        memory: 8Gi
                    readinessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /notebook/rhtap-app/testjul16-9-test/api
                        port: notebook-port
                        scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 1
                    name: testjul16-9-test
                    livenessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /notebook/rhtap-app/testjul16-9-test/api
                        port: notebook-port
                        scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 1
                    env:
                      - name: NOTEBOOK_ARGS
                        value: |-
                          --ServerApp.port=8888
                                            --ServerApp.token=''
                                            --ServerApp.password=''
                                            --ServerApp.base_url=/notebook/rhtap-app/testjul16-9-test
                                            --ServerApp.quit_button=False
                      - name: JUPYTER_IMAGE
                        value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2024.1'
                    ports:
                      - containerPort: 8888
                        name: notebook-port
                        protocol: TCP
                    imagePullPolicy: Always
                    volumeMounts:
                      - mountPath: /opt/app-root/src
                        name: testjul16-9-test
                      - mountPath: /dev/shm
                        name: shm
                    image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2024.1'
                    workingDir: /opt/app-root/src
                enableServiceLinks: false
                serviceAccountName: testjul16-9-test
                volumes:
                  - name: testjul16-9-test
                    persistentVolumeClaim:
                      claimName: testjul16-9-test-rhoai
                  - emptyDir:
                      medium: Memory
                    name: shm
          ---
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            annotations:
              openshift.io/display-name: testjul16-9-test-rhoai
            name: testjul16-9-test-rhoai
            labels:
              opendatahub.io/dashboard: 'true'
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            volumeMode: Filesystem
          EOF
          
      restartPolicy: Never